### ISSUE TITLE
SSL certificate problem: self signed certificate in certificate chain - issue with dynamically configure turn_off_ssl_verification

### ISSUE THREAD

**Issue by mits-techreceptives** [bryglen/yii2-sendgrid#11]
I am extending my wrapper class with this sendgrid . I have setup all configuration dyamically and works proper but i am facing above error . 
to resolve it , i have to manually set $options['turn_off_ssl_verification'] =  "True" to \vendor\sendgrid\lib\SendGrid.php's Constructor. 
How to configure this parameter dynamically from configuration or by any other way ??

**Comment by bryglen** [comment]
``` php
'options' => [
   'turn_off_ssl_verification' => true
]
```

see https://github.com/bryglen/yii2-sendgrid/blob/master/Mailer.php#L108

**Comment by mits-techreceptives** [comment]
Yeah.. Got it @bryglen  .
Thanks a lot !!
