### ISSUE TITLE
Object of class CURLFile could not be converted to string

### ISSUE THREAD

**Issue by ghost** [bryglen/yii2-sendgrid#13]
Hello,
When we implemented this package to send email with attachment, we received following error message,

Example code:

```
        $sendGrid = Yii::$app->sendGrid;
        $message = $sendGrid->compose('test');
        $message->setFrom([Yii::$app->params['supportEmail'] => 'Awesome project'])
            ->setTo('savemefromthisissue@gmail.com')
            ->setSubject("What's happening here?");


        $message->attach('/path/to/project/images/1.pdf');
        $message->send();
```

Thrown Exception:

> "PHP Recoverable Error – yii\base\ErrorException
> Object of class CURLFile could not be converted to string"

We tried every possible way but could not make it work. We may be doing it in wrong way but could not find a working solution. So, we decided to debug the package itself. We know it's bad to change package of vendor folder but we needed to fix this now.

In Message.php of this package, there is toString() method and it's trying to convert curl object to string which resulted to the error that we received. So, inside that function we changed following code

```
       foreach ($this->getSendGridMessage()->toWebFormat() as $key => $value) {
            $string .= sprintf("%s:%s\n", $key, $value);
        }
```

to

```
         foreach ($this->getSendGridMessage()->toWebFormat() as $key => $value) {
               if(is_object($key) || is_object($value)) {
                 continue;
              }
              
             $string .= sprintf("%s:%s\n", $key, $value);
        }
```

It solved our issue but we know that it's bad  to edit the packages of vendor folder  since it will get changed in next update. So, If this issue is genuine then please make this change. If we did it all wrong then please guide us with working solution. Thank you.

**Comment by bryglen** [comment]
can you make a PR? thank you

**Comment by ghost** [comment]
I was going to make PR. Even forked the repo. But seems like you have fixed it already. Saw the changes in latest update. Or maybe I didn't updated the package which had the fix merged.
