### ISSUE TITLE
Installing with composer is not pulling latest code. 

### ISSUE THREAD

**Issue by ghost** [bryglen/yii2-sendgrid#14]
Hi,

In previous issue that I reported , I just cloned it straight from Github and it worked. But, installing this repo with composer is not pulling latest code. We cleared the composer cache. So we are not getting the changes made by @harmosr. What's happening? Thanks.

**Comment by webremote** [comment]
Can be fixed if @bryglen creates a new tag, then packagist will be updated (hint, hint)

**Comment by bryglen** [comment]
Done!
