### ISSUE TITLE
Error: Class 'SendGrid\Email' not found

### ISSUE THREAD

**Issue by bureddysantosh** [bryglen/yii2-sendgrid#4]
Hi Team,

We are installed above "yii2-sendgrid" using composer.
And we are getting below error:
Class 'SendGrid\Email' not found

Here is my code;
$sendGrid = Yii::$app->sendGrid;  
$attributes = array('name' => "ABC", 'email' => "xyz@example.com");
$message = $sendGrid->compose('@app/views/email-templates/check.php', ['attributes' => $attributes]);

$message->setFrom('xx@example.com')
        ->setTo('xyz@example.com')
        ->setSubject('Thanks')  
        ->send($sendGrid);

**Comment by bryglen** [comment]
it looks like you have autoloading problem or so.

**Comment by bureddysantosh** [comment]
Yes, It's working fine now.
Thank you

**Comment by dudunegrinhu** [comment]
@bureddysantosh what did you do to make it work? I'm having the same problem.

**Comment by mits-techreceptives** [comment]
@bureddysantosh what did you do to make it work? I'm having the same problem.please help
