### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by BenasPaulikas** [bryglen/yii2-sendgrid#8]
'components' => [
    ...
    'sendGrid' => [
        'class' => 'bryglen\sendgrid\Mailer',
        'username' => 'your_user_name',
        'password' => 'your password here',
        //'viewPath' => '@app/views/mail', // your view path here
    ],
    ...
],

class here is wrong

**Comment by bryglen** [comment]
Whats wrong?

**Comment by BenasPaulikas** [comment]
When I downloaded it with composer the class in composer.json autoload psr4 was different than 'class' => 'bryglen\sendgrid\Mailer'. Now it's all good
